### ISSUE TITLE
Incompatible docker file: build_docker.sh

### ISSUE THREAD

**Issue by NicolasHHH** [cosynus-lix/f1tenth_quickstart#3]
**Issue description:** 
- Build failed

**To Reproduce:**
1. Follow the steps in ReadMe
2. Run  `./build_docker.sh` which gives error

**Comment by NicolasHHH** [comment]
**Solution found:**

[https://github.com/f1tenth/f1tenth_gym_ros/issues/14#issuecomment-803034138](url)

**Besides this, the following steps are necessary:**
1. System requirement: **Ubuntu 18.04 + ROS melodic** (failed to build the file with Ubuntu 20.04 + ROS noetic, please leave a comment if anyone succeeds the build with 20.04)
2. Delete the default `f1tenth_gym` folder (with a lock) via terminal before the build. 
3. Replace `build_docker.sh` with the codes in the given link above. 

**Remarks:** 

The new file from the link will check if there is `f1tenth_gym` and download it automatically if not. What makes a difference and solves the problem is the line: `git checkout cpp_backend_archive`

**Comment by nanli42** [comment]
:+1::+1::+1:
